### ISSUE TITLE
Webstorm shows links to wrong lines

### ISSUE THREAD

**Issue by tpluscode** [mcliment/typescript-karma-webpack-coverage-sample#1]
Hey! Thank you for this. I've been looking for a working setup for my project for ages.

Unfortunately the sourcemaps appear to be off. It's a problem I have face myself and managed to fix with webpack setting:

```js
const webpack = require('webpack');

module.exports = {
    plugins: [
        new webpack.SourceMapDevToolPlugin({
            filename: null,
            test: /\.(ts|js)($|\?)/i
        })
    ]
};
```

It works for me without coverage. Unfortunately adding Istanbul based on your example, the lines reported by webstorm are shifted. Check the screenshot, where it links to line `25` where it should be `51`.

<img width="1117" alt="screen shot 2019-01-23 at 17 32 44" src="https://user-images.githubusercontent.com/588128/51621699-5d445d80-1f35-11e9-921b-ab2651330429.png">

If I remove `SourceMapDevToolPlugin` then Webster does not pick up the mapping at all and only shows the `tests/Heracles-spec.ts:104987:9218` locations 🤔 

Have you been able to get similar this correct in any of your projects?

**Comment by tpluscode** [comment]
On the other hand debugging seems fine, albeit served from `webpack://` so webstorm breakpoints are ignored but stepping through is working as expected...

**Comment by mcliment** [comment]
I don't use Webstorm and in my debugging environment works fine. I'm not fixing this.
